// =============================================
//  Spell Quest — Word Bank
//  Add more words here to expand the quiz!
// =============================================

const words = [
  { word: "Sky",         wrong: ["Skey",     "Skky",      "Skie"]       },
  { word: "Air",         wrong: ["Aer",      "Aire",      "Ari"]        },
  { word: "Wind",        wrong: ["Wynd",     "Wend",      "Winnd"]      },
  { word: "Rain",        wrong: ["Rane",     "Rayn",      "Rainn"]      },
  { word: "Snow",        wrong: ["Snowe",    "Snaw",      "Snno"]       },
  { word: "Birds",       wrong: ["Byrds",    "Birdes",    "Birrds"]     },
  { word: "Drizzle",     wrong: ["Drizzal",  "Drizzel",   "Drizle"]     },
  { word: "Cloud",       wrong: ["Cloude",   "Kload",     "Claud"]      },
  { word: "Sun",         wrong: ["Sunn",     "Son",       "Sune"]       },
  { word: "Moon",        wrong: ["Moun",     "Muun",      "Moone"]      },
  { word: "River",       wrong: ["Rivar",    "Rivir",     "Rivver"]     },
  { word: "Fountain",    wrong: ["Fontain",  "Fountin",   "Fountian"]   },
  { word: "Sea",         wrong: ["See",      "Sie",       "Seaa"]       },
  { word: "Ocean",       wrong: ["Oceen",    "Ocian",     "Oshean"]     },
  { word: "Dawn",        wrong: ["Doun",     "Daun",      "Dawan"]      },
  { word: "Dusk",        wrong: ["Dask",     "Duusk",     "Dusck"]      },
  { word: "Morning",     wrong: ["Mornning", "Morrning",  "Morening"]   },
  { word: "Noon",        wrong: ["Nune",     "Nuun",      "Noone"]      },
  { word: "Evening",     wrong: ["Evning",   "Evining",   "Evenning"]   },
  { word: "Night",       wrong: ["Nite",     "Niight",    "Nightt"]     },
  { word: "Tree",        wrong: ["Trea",     "Tri",       "Treee"]      },
  { word: "Plant",       wrong: ["Plent",    "Plaant",    "Plannt"]     },
  { word: "Forest",      wrong: ["Forrest",  "Forast",    "Forset"]     },
  { word: "Mountain",    wrong: ["Mountian", "Mountin",   "Mowntain"]   },
  { word: "Hill",        wrong: ["Hil",      "Hiil",      "Hille"]      },
  { word: "Valley",      wrong: ["Valey",    "Vallay",    "Vallley"]    },
  { word: "Stone",       wrong: ["Stoan",    "Stoone",    "Stonne"]     },
  { word: "Rock",        wrong: ["Roke",     "Rokk",      "Rocc"]       },
  { word: "Soil",        wrong: ["Soile",    "Soyl",      "Soill"]      },
  { word: "Stars",       wrong: ["Stares",   "Starrs",    "Staars"]     },
  { word: "Branch",      wrong: ["Brunch",   "Barnch",    "Bransh"]     },
  { word: "Fruit",       wrong: ["Frut",     "Fruut",     "Froit"]      },
  { word: "Fog",         wrong: ["Fogg",     "Foge",      "Faug"]       },
  { word: "Dew",         wrong: ["Due",      "Dwe",       "Diw"]        },
  { word: "Grass",       wrong: ["Grasse",   "Gras",      "Graas"]      },
  { word: "Shrub",       wrong: ["Shrube",   "Shrubb",    "Shrob"]      },
  { word: "Flower",      wrong: ["Flawer",   "Flowur",    "Flowar"]     },
  { word: "Hail",        wrong: ["Hale",     "Haile",     "Haill"]      },
  { word: "Shower",      wrong: ["Showir",   "Shouver",   "Showar"]     },
  { word: "Rays",        wrong: ["Rayes",    "Rayz",      "Rais"]       },
  { word: "Altitude",    wrong: ["Altitood", "Altittude", "Altitiude"]  },
  { word: "Temperature", wrong: ["Temperture","Temprature","Tempurature"]},
  { word: "Atmosphere",  wrong: ["Atmosfere","Atmosfhere","Atmoshpere"] },
  { word: "Creeper",     wrong: ["Crieper",  "Creepir",   "Crepar"]     },
];
